name: server
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  # path: ^1.8.0
  mongo_dart: ^0.8.0
  shelf: ^1.4.0
  shelf_hotreload: ^1.3.0
  shelf_router: ^1.1.3
  shelf_web_socket: ^1.0.2
  web_socket_channel: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
